### PR TITLE
(optionally) show all cards the opponent played, not just the ones in the deck

### PR DESCRIPTION
**Pull request by BernsteinA**

### CODE REVIEW

**Comment by djdookie** [comment]
Hey @BernsteinA 
thanks for your contribution.
Could you please explain, why one would like to see non-matched but played cards instead of only complete matched decks in the advisor overlay?
All played cards can already be seen in the opponent's played cards list. In my opinion, this would only confuse people. 
I don't really get the idea/advantage. ;)

**Comment by BernsteinA** [comment]
I don't have the screen real estate to show both, so I turn off the opponent played card list

**Comment by djdookie** [comment]
Ah, now I see your motivation. :)

Unfortunately I think this is not the best solution for several reasons:

1. I don't like the idea that the plugin replaces or immitates some HDT core functionality, i.e. show played (opponent) cards.
2. You try to solve a spacing problem by mixing up clearly separated tasks. And btw. you need less horizontal space, but more vertical space.
Additionally, with two 'decorrelated' windows, you have a lot more sizing and placement options. The spacing problem can and should only be solved by resizing and/or replacing the windows, if you have only one screen. I for myself only use 1 Full HD screen for Hearthstone, and I place both windows (opponent list and advisor list) on the left side with a 70% scaling which works great! (So no overlapping with the card history bar).
3. The primary intention to guess and show a popular matching deck is somehow blurred by additional information/cards you normally get from the main tool (HDT). I didn't try it yet, but I think I would be confused by this. Later on I can't distinguish between greyed out (played) cards that have been in the original decklist and those that haven't.

Even if it's optional, I don't really like to have this feature in the main branch, sorry. But you're of course free to use your own fork for this.
I hope you understand my arguments and my position regarding this. But feel free to convince me! ;) Possibly post a screenshot of your view and tell me why it's useful!

**Comment by BernsteinA** [comment]
It's useful to me because I like to see which cards my opponent has substituted in their deck.
It's a clutter / repeated information issue to me as well; if the opponent is playing a deck exactly as predicted, then there is no new information in the default opponent played card list anyway.
I solved some of the visual confusion by making the non-matching cards red, instead of gray.

**Comment by BernsteinA** [comment]
capture
This is with size set to 110

**Comment by djdookie** [comment]
Can you post a screenshot of your plugin variant showing also non-matching red cards?
Where do you place those red cards? In between ordered by manacost oder at the end of the list?

Did you try size 70% and use the default opponent's cardlist AND Advisor overlay on the left side like I do?
It looks like this:

grafik

If I think about your pull request again, it could indeed (optionally) be helpful to see cardswaps more easy, if they're sorted by mana cost into the predicted list and visualized in red or another color...
I believe, most of the cardswaps are done with the same mana cost, right?
Now I'd really like to see a screenshot from you how this would look like in a later game state! ;)

**Comment by BernsteinA** [comment]
Sure, I'll get you that screenshot.
70% is useless to me; I can't read it that small, and I personally don't want to have two lists when I could get the same information in just one.

**Comment by djdookie** [comment]
Be careful: (now) it's not the same information!
For example, in the Advisor's list you can't see if one or two cards of the same type were played if a card is greyed-out. Or you can't see if zero or one cards were played if there's one card left in the Advisor's list.
You're extension would have to solve that too.

**Comment by BernsteinA** [comment]
It does

**Pull request closed without merging**
